# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "github.com/nunocoracao/blowfish/v2"
baseURL = "https://yagikota.github.io/blog/"
defaultContentLanguage = "en"
enableRobotsTXT = true
[pagination]
  pagerSize = 10
summaryLength = 30

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
