languageCode = "en"
languageName = "English"
weight = 1
title = "Kota's Blog"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01"
  description = "Kota's Blog | Kota Yagi"

[params.author]
name = "Kota Yagi"
image = "img/icon.jpg"
headline = "SRE @ Money Forward"
subtitle = "ðŸš€ Building reliable systems and the platforms that keep them running"
bio = "SRE @ Money Forward"
links = [
  { github = "https://github.com/yagikota" },
  { linkedin = "https://linkedin.com/in/yagikota/" },
  { x-twitter = "https://x.com/88888888_kota" },
]
