languageCode = "en"
languageName = "English"
weight = 1

[params]
  displayName = "EN"
  isoCode = "en"

[params.author]
  name = "yagikota"
  # image = "img/author.jpg"  # Uncomment after adding your photo to assets/img/author.jpg
  headline = "SRE / Platform Engineer"
  bio = "Writing about SRE, Platform Engineering, Kubernetes, and cloud infrastructure."
  links = [
    { github = "https://github.com/yagikota" },
    { linkedin = "https://linkedin.com/in/" },
    { x-twitter = "https://x.com/" },
  ]

title = "yagikota's blog"
