# -- Main Menu --

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 40
  [main.params]
    icon = "search"
